# Generated by Django 4.2.5 on 2023-09-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.CharField(default='https://static.vecteezy.com/system/resources/previews/005/337/799/original/icon-image-not-found-free-vector.jpg', max_length=512)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('rating', models.IntegerField(default=0)),
                ('sold', models.IntegerField(default=0)),
            ],
        ),
    ]
